Use the following dataset - https://www.kaggle.com/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews

In [3]:
# Problem 1
# Apply all the preprocessing techniques that you think are necessary
import pandas as pd
import requests

In [4]:
df = pd.DataFrame()
# !pip install --upgrade pandas
# !pip install pandas==2.0.3

In [5]:
df = pd.read_csv("/content/sample_data/IMDB Dataset.csv",encoding="latin-1",on_bad_lines="skip")

In [6]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [7]:
df.review[0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fa

In [8]:
df.info()
# df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB


In [9]:
df.duplicated().sum()

418

In [10]:
df.drop_duplicates(inplace=True)

In [11]:
!pip install contractions

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 289.9/289.9 kB 1.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.7/110.7 kB 10.3 MB/s eta 0:00:00


In [12]:
import contractions

def expand_contractions(text):
    # Use contractions.fix() to expand contractions in the text
    expanded_text = contractions.fix(text)
    return expanded_text

In [13]:
df["review"] = df["review"].apply(expand_contractions)
df

review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there is a family where a little boy...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I am going to have to disagree with the previo...  negative
49999  No one expects the Star Trek movies to be high...  negative

[49582 rows x 2 columns]

In [14]:
# convert into lower case
df['review'] = df['review'].str.lower()
df

review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. <br /><br />the...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there is a family where a little boy...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i am going to have to disagree with the previo...  negative
49999  no one expects the star trek movies to be high...  negative

[49582 rows x 2 columns]

In [15]:
# Remove HTML-tags
import re
def remove_html_tags(text):
  pattern = re.compile("<.*>")
  return pattern.sub(r'', text)

In [16]:
df["review"] = df["review"].apply(remove_html_tags)
df.review[0]

'one of the other reviewers has mentioned that after watching just 1 oz episode you will be hooked. they are right, as this is exactly what happened with me.i would say the main appeal of the show is due to the fact that it goes where other shows would not dare. forget pretty pictures painted for mainstream audiences, forget charm, forget romance...oz does not mess around. the first episode i ever saw struck me as so nasty it was surreal, i could not say i was ready for it, but as i watched more, i developed a taste for oz, and got accustomed to the high levels of graphic violence. not just violence, but injustice (crooked guards who will be sold out for a nickel, inmates who will kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) watching oz, you may become comfortable with what is uncomfortable viewing....that is if you can get in touch with your darker side.'

In [17]:
# Remove urls
def remove_urls(text):
  pattern = re.compile(r'https?://\S+|www\.\S+')
  return pattern.sub(r'',text)

In [18]:
df["review"] = df["review"].apply(remove_urls)
df.review[0]

'one of the other reviewers has mentioned that after watching just 1 oz episode you will be hooked. they are right, as this is exactly what happened with me.i would say the main appeal of the show is due to the fact that it goes where other shows would not dare. forget pretty pictures painted for mainstream audiences, forget charm, forget romance...oz does not mess around. the first episode i ever saw struck me as so nasty it was surreal, i could not say i was ready for it, but as i watched more, i developed a taste for oz, and got accustomed to the high levels of graphic violence. not just violence, but injustice (crooked guards who will be sold out for a nickel, inmates who will kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) watching oz, you may become comfortable with what is uncomfortable viewing....that is if you can get in touch with your darker side.'

In [19]:
import string
exclude = string.punctuation
print(exclude)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [20]:
def remove_punc(text):
  return text.translate(str.maketrans('','',exclude))

In [21]:
df["review"] = df["review"].apply(remove_punc)
df.review[0]

'one of the other reviewers has mentioned that after watching just 1 oz episode you will be hooked they are right as this is exactly what happened with mei would say the main appeal of the show is due to the fact that it goes where other shows would not dare forget pretty pictures painted for mainstream audiences forget charm forget romanceoz does not mess around the first episode i ever saw struck me as so nasty it was surreal i could not say i was ready for it but as i watched more i developed a taste for oz and got accustomed to the high levels of graphic violence not just violence but injustice crooked guards who will be sold out for a nickel inmates who will kill on order and get away with it well mannered middle class inmates being turned into prison bitches due to their lack of street skills or prison experience watching oz you may become comfortable with what is uncomfortable viewingthat is if you can get in touch with your darker side'

In [22]:
# Remove stopper
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [23]:
def remove_stopwords(text):
    new_text = []

    for word in text.split():
        if word in stopwords.words('english'):
            new_text.append('')
        else:
            new_text.append(word)
    x = new_text[:]
    new_text.clear()
    return " ".join(x)


In [24]:
df["review"] = df["review"].apply(remove_stopwords)
df.review[0]

'one    reviewers  mentioned   watching  1 oz episode    hooked   right    exactly  happened  mei would say  main appeal   show  due   fact   goes   shows would  dare forget pretty pictures painted  mainstream audiences forget charm forget romanceoz   mess around  first episode  ever saw struck    nasty   surreal  could  say   ready      watched   developed  taste  oz  got accustomed   high levels  graphic violence   violence  injustice crooked guards    sold    nickel inmates   kill  order  get away   well mannered middle class inmates  turned  prison bitches due   lack  street skills  prison experience watching oz  may become comfortable    uncomfortable viewingthat     get  touch   darker side'

In [25]:
df.head()

review sentiment
0  one    reviewers  mentioned   watching  1 oz e...  positive
1   wonderful little production  realism really c...  positive
2   thought    wonderful way  spend time    hot s...  positive
3  basically    family   little boy jake thinks  ...  negative
4  petter matteis love   time  money   visually s...  positive

In [26]:
# Tokenization
from nltk.tokenize import word_tokenize, sent_tokenize
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [57]:
df["tokenized_review"] = df['review'].apply(word_tokenize)

In [59]:
df["tokenized_review"][0]

['one',
 'reviewers',
 'mentioned',
 'watching',
 '1',
 'oz',
 'episode',
 'hooked',
 'right',
 'exactly',
 'happened',
 'mei',
 'would',
 'say',
 'main',
 'appeal',
 'show',
 'due',
 'fact',
 'goes',
 'shows',
 'would',
 'dare',
 'forget',
 'pretty',
 'pictures',
 'painted',
 'mainstream',
 'audiences',
 'forget',
 'charm',
 'forget',
 'romanceoz',
 'mess',
 'around',
 'first',
 'episode',
 'ever',
 'saw',
 'struck',
 'nasty',
 'surreal',
 'could',
 'say',
 'ready',
 'watched',
 'developed',
 'taste',
 'oz',
 'got',
 'accustomed',
 'high',
 'levels',
 'graphic',
 'violence',
 'violence',
 'injustice',
 'crooked',
 'guards',
 'sold',
 'nickel',
 'inmates',
 'kill',
 'order',
 'get',
 'away',
 'well',
 'mannered',
 'middle',
 'class',
 'inmates',
 'turned',
 'prison',
 'bitches',
 'due',
 'lack',
 'street',
 'skills',
 'prison',
 'experience',
 'watching',
 'oz',
 'may',
 'become',
 'comfortable',
 'uncomfortable',
 'viewingthat',
 'get',
 'touch',
 'darker',
 'side']

In [29]:
# Stemming
from nltk.stem.porter import PorterStemmer

In [70]:
ps = PorterStemmer()
def stem_words(text):
    return " ".join([ps.stem(word) for word in text])

In [71]:
df["tokenized_review"] = df['tokenized_review'].apply(stem_words)

In [72]:
df['tokenized_review']

0        one review mention watch 1 oz episod hook righ...
1        wonder littl product realism realli come home ...
2        thought wonder way spend time hot summer weeke...
3        basic famili littl boy jake think zombi closet...
4        petter mattei love time money visual stun film...
                               ...                        
49995    thought movi right good job creativ origin fir...
49996    bad plot bad dialogu bad act idiot direct anno...
49997    cathol taught parochi elementari school nun ta...
49998    go disagr previou comment side maltin one seco...
49999    one expect star trek movi high art fan expect ...
Name: tokenized_review, Length: 49582, dtype: object

In [73]:
# Problem 2
# Find out the number of words in the entire corpus and also the total number of unique words(vocabulary) using just python
total_words = len(df["tokenized_review"])
print("Total number of word in corpus =",total_words)

# Unique word in the corpus(Vocabulary)
unique_words = len(set(df["tokenized_review"]))
print("Total number of unique word in corpus =",unique_words)

Total number of word in corpus = 49582
Total number of unique word in corpus = 49538


In [74]:
# Problem 3
# Apply One Hot Encoding
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(handle_unknown='ignore')

In [75]:
enc_df = enc.fit_transform(df["tokenized_review"].values.reshape(-1, 1)).toarray()

In [76]:
enc_df

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [77]:
# Problem 4
# Apply bag words and find the vocabulary also find the times each word has occured
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [78]:
bow = cv.fit_transform(df['tokenized_review'])

In [79]:
print(cv.vocabulary_)
len(cv.vocabulary_)

{'one': 70432, 'review': 81619, 'mention': 61977, 'watch': 106316, 'oz': 72256, 'episod': 32090, 'hook': 46807, 'right': 82012, 'exactli': 33053, 'happen': 43833, 'mei': 61693, 'would': 109359, 'say': 84539, 'main': 59379, 'appeal': 7369, 'show': 88294, 'due': 29559, 'fact': 34058, 'goe': 41083, 'dare': 24691, 'forget': 37547, 'pretti': 77228, 'pictur': 74710, 'paint': 72451, 'mainstream': 59390, 'audienc': 8687, 'charm': 18499, 'romanceoz': 82747, 'mess': 62165, 'around': 7911, 'first': 36493, 'ever': 32773, 'saw': 84495, 'struck': 93812, 'nasti': 66630, 'surreal': 95136, 'could': 22647, 'readi': 79886, 'develop': 26455, 'tast': 96295, 'got': 41670, 'accustom': 3291, 'high': 45630, 'level': 56446, 'graphic': 41949, 'violenc': 105231, 'injust': 49467, 'crook': 23652, 'guard': 42588, 'sold': 90551, 'nickel': 67552, 'inmat': 49487, 'kill': 53577, 'order': 71079, 'get': 40210, 'away': 9102, 'well': 106997, 'manner': 59931, 'middl': 62545, 'class': 19872, 'turn': 101514, 'prison': 77384, '

111240

In [80]:
print(bow[0].toarray())
print(bow[1].toarray())

[[0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]


In [81]:
cv.transform(["They are right, as this is exactly what happened with me"]).toarray()

array([[0, 0, 0, ..., 0, 0, 0]])

In [95]:
# Problem 5
# Apply bag of bi-gram and bag of tri-gram and write down your observation about the dimensionality of the vocabulary
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))
# cv = CountVectorizer(ngram_range=(3,3))

In [96]:
bi_gram = cv.fit_transform(df['tokenized_review'])

In [97]:
len(cv.vocabulary_)

1721860